#image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/
    


build:
  stage: build
  tags:
    - shay
  script:
    - mvn $MAVEN_CLI_OPTS compile
    
test:
    stage: test
    tags:
    - test
    script:
        - mvn $MAVEN_CLI_OPTS test
        
scan:
  stage: test
  tags:
    - scan
  script:
    - mvn clean install
    - mvn sonar:sonar
    #- mvn --batch-mode verify sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_LOGIN -Dsonar.password=$SONAR_PASSWORD
  only:
    - master

deploy:
  stage: deploy
  tags:
    - deploy

  script:
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - master
