image: maven:latest

variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    


build:
  stage: build
  tags:
    - build
  script:
    - mvn package
    
test:
    stage: test
    tags:
    - test
    script:
        - mvn test
        
scan:
  stage: test
  tags:
    - scan
  script:
    - mvn clean verify sonar:sonar
  only:
    - master

.deploy:
  stage: deploy
  script:
    - mvn deploy
  only:
    - master
