#image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/
    
stages:
    - build
    - test
    - scan
    - publish
    - deploy

build:
  stage: build
  tags:
    - shay
    - tagA
  script:
    - pwd
    - echo $MAVEN_REPO_PASS
    - echo $MAVEN_REPO_URL
    - echo $MAVEN_REPO_USER
    - echo $CURR_IP
    - mvn $MAVEN_CLI_OPTS compile
    
test:
    stage: test
    tags:
    - test
    - tagB
    script:
        - mvn $MAVEN_CLI_OPTS test
        
scan:
  stage: test
  tags:
    - scan
  script:
    - mvn clean install
    - mvn sonar:sonar
    #- mvn --batch-mode verify sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_LOGIN -Dsonar.password=$SONAR_PASSWORD
  only:
    - master

publish:
  stage: publish
  tags:
    - publish

  script:
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - master
    
deploy:
  stage: deploy
  tags:
    - deploy

  script:
    - mvn tomcat:deploy
    - mvn tomcat:run
  only:
    - master
